INSERT INTO review (id, rating, comment, user_id, experience_id) VALUES
(1, 5, '¡Una experiencia increíble! La cena en El Celler de Can Roca fue inolvidable.', 1, 1),
(2, 4, 'El masaje fue muy relajante, aunque esperaba un poco más de tiempo.', 2, 2),
(3, 5, 'El yoga al amanecer en la playa fue mágico. Totalmente recomendado.', 3, 3),
(4, 3, 'La excursión a los Picos de Europa fue buena, pero el guía no fue muy claro.', 1, 4),
(5, 5, 'El kayak en el río Ebro fue divertido y emocionante. ¡Volvería a hacerlo!', 2, 5),
(6, 4, 'El partido en el Camp Nou fue genial, pero las entradas eran un poco caras.', 3, 6),
(7, 5, 'La escalada en Margalef fue todo un desafío. ¡Me encantó!', 1, 7),
(8, 4, 'La visita al Museo del Prado fue interesante, aunque había mucha gente.', 2, 8),
(9, 5, 'El taller de flamenco en Sevilla fue muy divertido y bien organizado.', 3, 9),
(10, 3, 'La LAN Party estuvo bien, pero el espacio era un poco pequeño.', 1, 10),
(11, 5, 'El tour de tapas por el Barrio Gótico fue delicioso. ¡Comimos de todo!', 2, 11),
(12, 4, 'El retiro de meditación fue relajante, aunque el alojamiento podría mejorar.', 3, 12),
(13, 5, 'La clase de surf en Zarautz fue increíble. Los instructores son muy profesionales.', 1, 13),
(14, 4, 'El parapente en los Alpes fue emocionante, pero el precio es algo elevado.', 2, 14),
(15, 5, 'La visita al Teatro Romano de Mérida fue fascinante. ¡Muy recomendada!', 3, 15),
(16, 5, '¡Una experiencia increíble! La cena en El Celler de Can Roca fue exquisita. El servicio impecable y los platos una obra de arte.', 1, 1),
(17, 4, 'El masaje en el spa fue muy relajante, aunque esperaba un poco más de tiempo. El entorno natural es precioso.', 2, 2),
(18, 5, 'El yoga al amanecer en la playa fue mágico. El instructor muy profesional y el ambiente inmejorable. ¡Repetiré!', 3, 3),
(19, 3, 'La excursión a los Picos de Europa fue bonita, pero el guía no fue muy claro con las indicaciones. Las vistas espectaculares.', 1, 4),
(20, 5, 'El kayak en el río Ebro fue divertido y relajante. Los monitores muy atentos y el paisaje increíble.', 2, 5),
(21, 4, 'El partido en el Camp Nou fue una pasada, pero las entradas eran un poco caras. La atmósfera del estadio es única.', 3, 6),
(22, 5, 'La escalada en Margalef fue todo un reto. Los guías muy profesionales y el lugar es impresionante. ¡Volveré!', 1, 7),
(23, 4, 'La visita al Museo del Prado fue muy interesante, aunque faltó tiempo para ver todo. Las obras son impresionantes.', 2, 8),
(24, 5, 'El taller de flamenco en Sevilla fue muy divertido. La profesora era muy amable y aprendí mucho. ¡Recomendado!', 3, 9),
(25, 3, 'La LAN Party estuvo bien, pero el espacio era un poco pequeño. Aún así, lo pasamos genial jugando toda la noche.', 1, 10),
(26, 5, 'El tour de tapas por el Barrio Gótico fue una delicia. Probamos platos increíbles y el guía muy simpático.', 2, 11),
(27, 4, 'El retiro de meditación en la montaña fue relajante, aunque el alojamiento podría mejorar. El entorno es precioso.', 3, 12),
(28, 5, 'La clase de surf en Zarautz fue increíble. Los instructores muy profesionales y las olas perfectas para aprender.', 1, 13),
(29, 4, 'El parapente en los Alpes fue una experiencia única, aunque un poco corta. Las vistas son alucinantes.', 2, 14),
(30, 5, 'La visita al Teatro Romano de Mérida fue fascinante. El guía muy informativo y el lugar está muy bien conservado.', 3, 15),
(31, 4, 'La fiesta en la discoteca flotante fue muy divertida, aunque la música podría ser más variada. El ambiente es increíble.', 1, 16),
(32, 5, 'El concierto acústico en la bodega fue una experiencia íntima y especial. Los músicos eran muy talentosos.', 2, 17),
(33, 3, 'El torneo de videojuegos retro estuvo bien, pero faltaron más consolas. Aún así, lo pasamos genial.', 3, 18),
(34, 5, 'La cata de vinos en Ribera del Duero fue una experiencia única. Los vinos exquisitos y el anfitrión muy amable.', 1, 19),
(35, 4, 'El escape room fue muy divertido, aunque algunos acertijos eran demasiado difíciles. El equipo lo pasó genial.', 2, 20);